version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    environment:
      - DB_URL=sqlite:///./database.db

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "7654:7654"
    depends_on:
      - backend
